#!/usr/bin/env bash

#count=1
#while [[ $count -le $# ]]; do
#    echo "Argument $count: ${!count}"
#    count=$((count + 1))
#done

factor_finder(){
    if [ $# -ne 3 ]
    then
        argv="#@"
        count=0
        num2=1
        for arg in ${argv[*]};
        do
            if [ $count -gt 1 ]
            then
                num2=$(echo $num2 * $arg | bc)
            fi
            count=$((count + 1))
        done
    else
        num2=$3
    fi

    num1=$2
    num=$(echo "$1" | tr ';' '=')

    result=$(echo "if($num1 > $num2) 1 else 0" | bc)
        if [ $result -eq 1 ]
        then
            numcp=$num1
            num1=$num2
            num2=$numcp
        fi
    echo "$num$num1*$num2"
}

if [ $# -ne 1 ]
then
    echo "Usage: $0 <number>"
    exit 1
fi  
while read i
do
    input=$(factor "$i")
    factor_finder $input
    #echo "$input"
done < "$1"
