#!/usr/bin/env bash

#count=1
#while [[ $count -le $# ]]; do
#    echo "Argument $count: ${!count}"
#    count=$((count + 1))
#done

factor_finder(){
    if [ $# -ne 3 ]
    then
        argv="#@"
        count=0
        number_1=1
}

if [ $# -ne 1 ]
then
    echo "Usage: $0 <number>"
    exit 1
fi  
while read i
do
    input=$(factor "$i")
    factor_finder $input
    echo "$input"
done < "$1"
